import { useState } from "react";
import { TriviaQuestion } from "./TriviaQuestion";
import type { Question } from "./TriviaQuestion";

type Difficulty = "easy" | "medium" | "hard";
type Stage = "home" | "loading" | "quiz" | "results";

const DIFFICULTY_DESCRIPTIONS = {
  easy: "Basic NBA facts, team names, famous players. Great for casual fans.",
  medium: "Stats, records, draft history, playoff moments. For regular watchers.",
  hard: "Deep cuts — obscure records, trade history, draft picks, advanced stats.",
};

async function generateQuestions(difficulty: Difficulty): Promise<Question[]> {
  const API_BASE = import.meta.env.VITE_API_URL || "http://localhost:8000";

  const response = await fetch(`${API_BASE}/api/trivia/generate`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ difficulty }),
  });

  if (!response.ok) {
    const err = await response.json().catch(() => ({ detail: "Unknown error" }));
    throw new Error(err.detail ?? `HTTP ${response.status}`);
  }

  const data = await response.json();
  return data.questions;
}

export function TriviaPage() {
  const [stage, setStage] = useState<Stage>("home");
  const [difficulty, setDifficulty] = useState<Difficulty>("medium");
  const [questions, setQuestions] = useState<Question[]>([]);
  const [currentIdx, setCurrentIdx] = useState(0);
  const [score, setScore] = useState(0);
  const [error, setError] = useState<string | null>(null);

  const handleStart = async () => {
    setStage("loading");
    setError(null);
    try {
      const qs = await generateQuestions(difficulty);
      setQuestions(qs);
      setCurrentIdx(0);
      setScore(0);
      setStage("quiz");
    } catch (e) {
      setError(String(e));
      setStage("home");
    }
  };

  const handleAnswer = (correct: boolean) => {
    if (correct) setScore((s) => s + 1);
    if (currentIdx + 1 >= questions.length) {
      setTimeout(() => setStage("results"), 300);
    } else {
      setTimeout(() => setCurrentIdx((i) => i + 1), 300);
    }
  };

  const handleRestart = () => {
    setStage("home");
    setQuestions([]);
    setCurrentIdx(0);
    setScore(0);
  };

  // Home screen
  if (stage === "home") {
    return (
      <div className="flex-1 flex flex-col items-center justify-center px-8 max-w-xl mx-auto w-full">
        <div className="font-mono text-xs text-text-secondary tracking-wider mb-3">
          NBA · WIN PROBABILITY ENGINE
        </div>
        <h1 className="text-4xl font-bold mb-2 text-center">NBA Trivia</h1>
        <p className="text-text-secondary text-center mb-10 leading-relaxed">
          10 questions generated by AI. New questions every time.
        </p>

        <div className="w-full mb-8">
          <div className="font-mono text-xs text-text-secondary tracking-wider mb-3">
            DIFFICULTY
          </div>
          <div className="flex flex-col gap-3">
            {(["easy", "medium", "hard"] as Difficulty[]).map((d) => (
              <button
                key={d}
                onClick={() => setDifficulty(d)}
                className={`w-full text-left px-5 py-4 border transition-colors ${
                  difficulty === d
                    ? "border-prob-win text-text-primary"
                    : "border-[#2A2E3D] text-text-secondary hover:border-text-secondary"
                }`}
              >
                <div className="font-mono text-sm font-bold mb-1 uppercase tracking-wider">
                  {d}
                </div>
                <div className="text-xs text-text-secondary">
                  {DIFFICULTY_DESCRIPTIONS[d]}
                </div>
              </button>
            ))}
          </div>
        </div>

        {error && (
          <div className="w-full mb-4 px-4 py-3 border border-prob-loss font-mono text-xs text-prob-loss">
            {error}
          </div>
        )}

        <button
          onClick={handleStart}
          className="w-full py-4 border border-prob-win text-prob-win font-mono text-sm tracking-wider hover:bg-prob-win hover:text-black transition-colors"
        >
          START QUIZ →
        </button>
      </div>
    );
  }

  // Loading screen
  if (stage === "loading") {
    return (
      <div className="flex-1 flex flex-col items-center justify-center gap-4">
        <div className="font-mono text-xs text-text-secondary tracking-wider animate-pulse">
          GENERATING QUESTIONS…
        </div>
        <div className="font-mono text-xs text-text-secondary">
          Generating your {difficulty} quiz
        </div>
      </div>
    );
  }

  // Quiz screen
  if (stage === "quiz" && questions[currentIdx]) {
    return (
      <div className="flex-1 flex flex-col min-h-0">
        <div className="px-8 py-4 border-b border-[#1F2230] flex items-center justify-between">
          <div className="font-mono text-xs text-text-secondary tracking-wider uppercase">
            {difficulty} · {currentIdx + 1}/{questions.length}
          </div>
          <div className="font-mono text-xs text-text-secondary">
            Score: {score}/{currentIdx}
          </div>
        </div>
        <div className="flex-1 overflow-y-auto">
          <TriviaQuestion
            key={currentIdx}
            question={questions[currentIdx]}
            number={currentIdx + 1}
            total={questions.length}
            onAnswer={handleAnswer}
          />
        </div>
      </div>
    );
  }

  // Results screen
  if (stage === "results") {
    const pct = Math.round((score / questions.length) * 100);
    const grade =
      pct >= 90 ? "NBA HISTORIAN" :
      pct >= 70 ? "SERIOUS FAN" :
      pct >= 50 ? "CASUAL WATCHER" :
      "ROOKIE";

    const gradeColor =
      pct >= 90 ? "text-prob-win" :
      pct >= 70 ? "text-prob-neutral" :
      "text-prob-loss";

    return (
      <div className="flex-1 flex flex-col items-center justify-center px-8 max-w-xl mx-auto w-full text-center">
        <div className="font-mono text-xs text-text-secondary tracking-wider mb-4">
          QUIZ COMPLETE
        </div>
        <div className={`font-mono text-6xl font-bold mb-2 ${gradeColor}`}>
          {score}/{questions.length}
        </div>
        <div className={`font-mono text-lg tracking-wider mb-2 ${gradeColor}`}>
          {grade}
        </div>
        <div className="text-text-secondary mb-10">
          {pct}% correct on {difficulty} difficulty
        </div>

        <div className="w-full flex flex-col gap-3">
          <button
            onClick={handleStart}
            className="w-full py-4 border border-prob-win text-prob-win font-mono text-sm tracking-wider hover:bg-prob-win hover:text-black transition-colors"
          >
            PLAY AGAIN (NEW QUESTIONS)
          </button>
          <button
            onClick={handleRestart}
            className="w-full py-4 border border-[#2A2E3D] text-text-secondary font-mono text-sm tracking-wider hover:border-text-secondary hover:text-text-primary transition-colors"
          >
            CHANGE DIFFICULTY
          </button>
        </div>
      </div>
    );
  }

  return null;
}